### ISSUE TITLE
Latest instructions

### ISSUE THREAD

**Issue by metallicusdev** [uuosio/ipyeos#3]
Whaat are the latest instructions to run this?

Following doesn't work
```
git clone https://github.com/uuosio/ipyeos --branch main --recursive
cd eos
./build.sh
cd ..
./build.sh
```

Not sure how to get `eosnode` and `eosdebugger` commands

**Comment by ghost** [comment]
Hello, please take a look at the updated document here:

https://github.com/uuosio/ipyeos#building

Let me know if you have any further issues or questions.
